version: '3.1'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 420024Jo
      MYSQL_DATABASE: BRITO
      MYSQL_USER:
      MYSQL_PASSWORD:

